version: "3.7"

services:
  micrapp_backend:
    image: micrapp_backend:test
    container_name: micrapp_test
    ports:
      - 3500:3500
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_DATABASE: micrapp_server_test
      DB_HOST: mysql
      NODE_ENV: test

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: micrapp_server_test